# Traefik configuration for Tiation Rigger Development Environment
# Handles load balancing and reverse proxy with dark neon theme dashboard

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  debug: true
  insecure: true

# Entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default

# Certificate resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: dev@tiation.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

# Provider configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: tiation-network
    
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Logging
log:
  level: INFO
  format: json
  filePath: /var/log/traefik.log

# Access logs
accessLog:
  filePath: /var/log/traefik-access.log
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Tracing
tracing:
  jaeger:
    samplingServerURL: http://jaeger:14268/api/sampling
    localAgentHostPort: jaeger:6831

# Pilot configuration (optional)
pilot:
  dashboard: false
